#!/usr/bin/env bash

# A script to upgrade an apt based image

apt-get update                                && \
apt-get upgrade -y                            && \
apt-get autoremove -y                         && \
apt-get clean                                 && \
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

